name: Example 2
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build_and_push_to_registry:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
          echo "Working On ${{ env.BRANCH_NAME }}"

      - name: Install nixpacks
        run: |
          curl -sSL https://nixpacks.com/install.sh | bash

      - name: Build with nixpacks
        run: |
          nixpacks build ./example_2/python-numgen --name tinyflow-ex2-py-numgen
          nixpacks build ./example_2/node-operation --name tinyflow-ex2-node-op

      - name: Save Docker image
        run: |
          mkdir /tmp/docker-images
          docker save tinyflow-ex2-py-numgen:latest > /tmp/docker-images/tinyflow-ex2-py-numgen.tar
          docker save tinyflow-ex2-node-op:latest > /tmp/docker-images/tinyflow-ex2-node-op.tar

      - name: Load Docker image
        run: |
          docker load -i /tmp/docker-images/tinyflow-ex2-py-numgen.tar
          docker tag tinyflow-ex2-py-numgen jalvarado91/tinyflow-ex2-py-numgen:latest
          docker load -i /tmp/docker-images/tinyflow-ex2-node-op.tar
          docker tag tinyflow-ex2-node-op jalvarado91/tinyflow-ex2-node-op:latest

      - name: Docker push
        run: |
          docker push jalvarado91/tinyflow-ex2-py-numgen:latest
          docker push jalvarado91/tinyflow-ex2-node-op:latest
