on:
  push:
    branches:
      - main
jobs:
  build_and_push_to_registry:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
          echo "Working On ${{ env.BRANCH_NAME }}"

      - name: Install nixpacks
        run: |
          curl -sSL https://nixpacks.com/install.sh | bash

      - name: Build with nixpacks
        run: |
          nixpacks build ./example_1/python-numpy --name tinyflow-ex1-python
          nixpacks build ./example_1/node-main-file --name tinyflow-ex1-node

      - name: Save Docker image
        run: |
          mkdir /tmp/docker-images
          docker save tinyflow-ex1-python:latest > /tmp/docker-images/tinyflow-ex1-python.tar
          docker save tinyflow-ex1-node:latest > /tmp/docker-images/tinyflow-ex1-node.tar

      - name: Load Docker image
        run: |
          docker load -i /tmp/docker-images/tinyflow-ex1-python.tar
          docker tag tinyflow-ex1-python ghcr.io/${{ github.repository }}/tinyflow-ex1-python:${{ env.BRANCH_NAME }}
          docker load -i /tmp/docker-images/tinyflow-ex1-node.tar
          docker tag tinyflow-ex1-node ghcr.io/${{ github.repository }}/tinyflow-ex1-node:${{ env.BRANCH_NAME }}

      - name: Docker push
        run: |
          docker push ghcr.io/${{ github.repository }}/tinyflow-ex1-python:${{ env.BRANCH_NAME }}
          docker push ghcr.io/${{ github.repository }}/tinyflow-ex1-node:${{ env.BRANCH_NAME }}
